# This file is for local (with cpu) environment.

version: '3.3'

services:
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    image: text2img/frontend
    command: app.py
    ports:
      - "8501:8501"
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: /tmp/keys/keyfile.json      
      BACKEND_URL: http://backend:80
    volumes:
      - ${GCP_KEY_PATH}:/tmp/keys/keyfile.json:ro
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile.local
    image: text2img/backend
    command: uvicorn app.main:app --host 0.0.0.0 --port 80
    ports:
      - "80:80"
