# This file is for local (with cpu) environment.

version: '3.3'

services:
  frontend:
    build: ./frontend/.
    image: text2img/frontend
    command: app.py
    ports:
      - "8501:8501"
    environment:
      - BACKEND_URL=http://backend:80
  backend:
    build:
      context: ./backend/.
      dockerfile: Dockerfile.cpu
    image: text2img/backend
    command: uvicorn app.main:app --host 0.0.0.0 --port 80
    ports:
      - "80:80"
