version: '3.3'

services:
  frontend:
    build: ./frontend/.
    image: text2img/frotend
    command: app.py
    ports:
      - "8501:8501"
  backend:
    build: ./backend/.
    image: text2img/backend
    command: uvicorn app.main:app --host 0.0.0.0 --port 80
    ports:
      - "80:80"
    deploy:
      resources:
        limits:
          memory: 5G
